name: Run tests in bazel
on: [push, pull_request]

jobs:
  build:
    name: Run tests in bazel
    strategy:
      matrix:
        worker: [tests, c7n_gcp_tests, c7n_kube_tests, c7n_mailer_tests]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
      - name: Execute bazel test //tests
        if: matrix.worker == 'tests'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build test //tests
      - name: Execute bazel test //tools/c7n_gcp/tests
        if: matrix.worker == 'c7n_gcp_tests'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build test //tools/c7n_gcp/tests
      - name: Execute bazel test //tools/c7n_kube/tests
        if: matrix.worker == 'c7n_kube_tests'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build test //tools/c7n_kube/tests
      - name: Execute bazel test //tools/c7n_mailer/tests
        if: matrix.worker == 'c7n_mailer_tests'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build test //tools/c7n_mailer/tests
